past_verb = input("Enter a past verb: ")
adjective1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
verb2 = input("Enter another verb: ")
b_name = input("Enter bride's name: ")
adjective2 = input("Enter an adjective: ")
adjective3 = input("Enter another adjective: ")
verb3 = input("Enter a verb: ")
noun2 = input("Enter a noun: ")
noun3 = input("Enter a feeling type noun: ")
print("\nWhen I found out you were getting married, I ", past_verb, ".")
print("You two are the most ",adjective1, " couple, and I wish you every")
print(noun1, " together. My advice for wedding bliss? Here goes! ")
print("Always ", verb1, " before bed, and don't forget to ",verb2,)
print("each other. I know ",b_name," will make the perfect wife, as")
print("she is so ", adjective2, " and ", adjective3, ". Remember to always")
print("",verb3, " each other, and never fight about ",noun2, ".")
print("I wish you so much ",noun3," in the years to come.")
